image:
  - Visual Studio 2013

build:
  parallel: true
  verbosity: detailed

environment:
  matrix:
    - platform: x86
      glib-url: http://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.28/glib_2.28.8-1_win32.zip
      glib-dev-url: http://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.28/glib-dev_2.28.8-1_win32.zip
      pkg-config-url: http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip
      gettext-url: http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/gettext-runtime_0.18.1.1-2_win32.zip
      proxy-libintl-dev-url: http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/proxy-libintl-dev_20100902_win32.zip
      libsndfile-url: http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28-w32.zip

    - platform: x64
      glib-url: http://ftp.gnome.org/pub/gnome/binaries/win64/glib/2.26/glib_2.26.1-1_win64.zip
      glib-dev-url: http://ftp.gnome.org/pub/gnome/binaries/win64/glib/2.26/glib-dev_2.26.1-1_win64.zip
      pkg-config-url: http://ftp.gnome.org/pub/gnome/binaries/win64/dependencies/pkg-config_0.23-2_win64.zip
      gettext-url: http://ftp.gnome.org/pub/gnome/binaries/win64/dependencies/gettext-runtime_0.18.1.1-2_win64.zip
      proxy-libintl-dev-url: http://ftp.gnome.org/pub/gnome/binaries/win64/dependencies/proxy-libintl-dev_20100902_win64.zip
      libsndfile-url: http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28-w64.zip
      
init:
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%

install:
# make sure the latest version of git is installed
  - choco upgrade git -y
  - mkdir c:\deps
  - cd c:\deps
  - curl -fsS -o glib.zip %glib-url%
  - curl -fsS -o glib-dev.zip %glib-dev-url%
  - curl -fsS -o pkg-config.zip %pkg-config-url%
  - curl -fsS -o gettext.zip %gettext-url%
  - curl -fsS -o libintl-dev.zip %proxy-libintl-dev-url%
  - curl -fsS -o libsndfile-dev.zip %libsndfile-url%
  - 7z x glib.zip > NUL
  - 7z x glib-dev.zip > NUL
  - 7z x pkg-config.zip > NUL
  - 7z x gettext.zip > NUL
  - 7z x libintl-dev.zip > NUL
  - 7z x libsndfile-dev.zip > NUL
# need to fix the naming of libsndfile otherwise the linker won't find it
  - move lib\libsndfile-1.lib lib\sndfile-1.lib
  - move lib\libsndfile-1.def lib\sndfile-1.def
  - SET PATH=C:\deps\bin;%PATH%
  - if "%platform%"=="x64" ( SET "PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%" ) else ( SET "PATH=C:\MinGW\bin;%PATH%" )

build_script:
#  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
#  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - cd C:\projects\fluidsynth-rjimi
  - mkdir build
  - cd build
# remove that path from PATH to make sure sh.exe is not found (cmake will complain otherwise)
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - echo %PATH%
  - echo %CFLAGS%
  - cmake -G "MinGW Makefiles" -DCMAKE_VERBOSE_MAKEFILE=1 ..
  - mingw32-make.exe all && mingw32-make.exe check

after_build:
  - 7z a fluidsynth-mingw-%platform%.zip %APPVEYOR_BUILD_FOLDER%\build\src\*fluidsynth* %APPVEYOR_BUILD_FOLDER%\build\fluidsynth.pc c:\deps\bin\libglib*.dll c:\deps\bin\libgthread*.dll c:\deps\bin\*intl*.dll

artifacts:
  - path: build/fluidsynth-mingw-%platform%.zip
    name: FluidSynth
