
name: optimlib-docs

channels:
  - conda-forge

dependencies:
  - doxygen=1.9.3
  - pip:
    - sphinx==5.1.1
    - breathe==4.34.0
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-katex==0.8.6
    - sphinxcontrib-contentui==0.2.5
    - docutils==0.17.1